OLD_NAME="Vivek-k001"
CORRECT_NAME="nidha-1001"
CORRECT_EMAIL="nidhaknidhak321@gmail.com"

if [ "$GIT_COMMITTER_NAME" = "$OLD_NAME" ] || [ "$GIT_AUTHOR_NAME" = "$OLD_NAME" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
